# Generated by Django 4.1.7 on 2023-03-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_remove_menuitem_category"),
    ]

    operations = [
        migrations.DeleteModel(name="Category",),
    ]
