# Generated by Django 4.1.7 on 2023-03-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0007_menuitem_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="menuitem", name="category",),
    ]
